name       : libevdev
version    : 1.9.0
release    : 13
source     :
    - https://www.freedesktop.org/software/libevdev/libevdev-1.9.0.tar.xz : e7e18a64264f2dea19b6c50a481f8c062529d42919ccda0bc861495bce28eb9e
homepage   : https://www.freedesktop.org/wiki/Software/libevdev/
license    :
    - GPL-2.0-only WITH Linux-syscall-note
    - MIT
component  : xorg.library
summary    : Wrapper library for evdev devices
description: |
    libevdev is a wrapper library for evdev devices. it moves the common tasks when dealing with evdev devices into a library and provides a library interface to the callers, thus avoiding erroneous ioctls, etc.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
