name       : libevdev
version    : 1.5.9
release    : 8
source     :
    - https://www.freedesktop.org/software/libevdev/libevdev-1.5.9.tar.xz : e1663751443bed9d3e76a4fe2caf6fa866a79705d91cacad815c04e706198a75
homepage   : www.freedesktop.org/wiki/Software/libevdev/
license    :
    - GPL-2.0-only
    - MIT
component  : xorg.library
summary    : Wrapper library for evdev devices
description: |
    libevdev is a wrapper library for evdev devices. it moves the common tasks when dealing with evdev devices into a library and provides a library interface to the callers, thus avoiding erroneous ioctls, etc.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
