name       : libevdev
version    : 1.7.0
release    : 10
source     :
    - https://www.freedesktop.org/software/libevdev/libevdev-1.7.0.tar.xz : 11dbe1f2b1d03a51f3e9a196757a75c3a999042ce34cf1fdc00a2363e5a2e369
homepage   : https://www.freedesktop.org/wiki/Software/libevdev/
license    :
    - GPL-2.0-only WITH Linux-syscall-note
    - MIT
component  : xorg.library
summary    : Wrapper library for evdev devices
description: |
    libevdev is a wrapper library for evdev devices. it moves the common tasks when dealing with evdev devices into a library and provides a library interface to the callers, thus avoiding erroneous ioctls, etc.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
