name       : libevdev
version    : 1.6.0
release    : 9
source     :
    - https://www.freedesktop.org/software/libevdev/libevdev-1.6.0.tar.xz : f5005c865987d980cc1279b9ec6131b06a89fd9892f649f2a68262b8786ef814
homepage   : https://www.freedesktop.org/wiki/Software/libevdev/
license    :
    - GPL-2.0-only WITH Linux-syscall-note
    - MIT
component  : xorg.library
summary    : Wrapper library for evdev devices
description: |
    libevdev is a wrapper library for evdev devices. it moves the common tasks when dealing with evdev devices into a library and provides a library interface to the callers, thus avoiding erroneous ioctls, etc.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
