name        : libevdev
version     : 1.4.4
release     : 4
source     :
    - http://www.freedesktop.org/software/libevdev/libevdev-1.4.4.tar.xz : ed9979369b6a6e28f5897d099538549ecffb2b7c00c1b717eb77c31d85bc45a9
homepage    : www.freedesktop.org/wiki/Software/libevdev/
license     :
    - GPL-2.0
summary     : Wrapper library for evdev devices
description : |
    libevdev is a wrapper library for evdev devices. it moves the common tasks when dealing with evdev devices into a library and provides a library interface to the callers, thus avoiding erroneous ioctls, etc.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
